const mongoose = require("mongoose");
const { Schema } = mongoose;

const AlbumSchema = new mongoose.Schema({
  title: {
    type: String,
    required: true,
  },
  author: {
    type: Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  description: {
    type: String,
    required: false,
  },
  podcastsList: [
    {
      type: Schema.Types.ObjectId, // Schema.types.ObjectId is used to refer to _id of the other podcasts 
                                   // that is automatically generated by MongoDB to other podcasts while creation 
      ref: 'Podcast', // tells the name of the model for reference rest mongoose will handle
      required: true,
    },
  ],
  thumbnailURL: {
    type: String,
    required: true,
  },
  likes: {
    type: Number,
    default: 0,
  },
  releaseDate: {
    type: Date,
    required: true,
  },
});

AlbumSchema.index({ likes: -1 });  // for easier sorting by likes
AlbumSchema.index({ releaseDate: -1 });  // for easier sorting by release date
AlbumSchema.index({ title: 'text'});  // for easier searching by album name
AlbumSchema.index({ author: 1 });   // for easier searching by author

const Album = mongoose.model("Album", AlbumSchema);

module.exports = Album;
